### PR TITLE
Add synchronize() implementation with MPI_Sendrecv

### PR DESCRIPTION
**Pull request by hmt23**
For now, we have to set the ARCANE_SYNCHRONIZE_VERSION to 2 to enable this code:

export ARCANE_SYNCHRONIZE_VERSION=2

### CODE REVIEW

**Comment by grospelliergilles** [comment]
It seems ARCANE_SYNCHRONIZE_VERSION is not used. Is the current version still available ?

**Comment by hmt23** [comment]
You added this variable here : `arcane/src/arcane/parallel/mpi/MpiParallelMng.cc:115:    if (platform::getEnvironmentVariable("ARCANE_SYNCHRONIZE_VERSION")=="2")` . 

MpiLegacyVariableSynchronizeDispatcher.cc is still available but the older version of MpiVariableSynchronizeDispatcher.cc will be deleted.

Are you ok with that ?

**Comment by grospelliergilles** [comment]
I prefer not to remove this version even it is not yet used. It may be useful for comparison and this new version will not work if we want to do non blocking synchronization. So you need to do a new class with your implementation and use it when `ARCANE_SYNCHRONIZE_VERSION=3`.

Two more things:
- indent with 2 space instead of 4 (you can use `clang-format`.
- add time statistics with the name 'SyncWait' to be able to know how much time is spent in synchronizations.

**Comment by hmt23** [comment]
I will make another PR with the changes to have better history on commits

**Comment by grospelliergilles** [comment]
Ok but you can keep this PR if you want and do a 'push --force' to change history

**Comment by hmt23** [comment]
Ok, I will do that.

**Comment by grospelliergilles** [comment]
It seems Ok.
Only one thing to change: the name `MpiNew*` should be changed with a more explicit name. For example `MpiDirectSendRecv*`. If we add a new version with `MPI_Neighbor` call it will help.

**Comment by hmt23** [comment]
I replace New by DirectSendrecv. I will make the neighbor one soon.

**Pull request merged**
